// ============================================================
// AI FOUNDATION MODEL LANDSCAPE — STRUCTURED COMPANY DATA
// Source: Global_AI_Foundation_Model_Landscape_2026_UPDATED.xlsx
// ============================================================

// Last auto-updated by GitHub Actions (ISO timestamp, null = never)
const LAST_AUTO_UPDATED = "2026-06-12T10:00:41.437Z";

// Helper: local logo path from slug
function getLogoUrl(slug) {
  return `logos/${slug}.png`;
}

const COMPANIES = [
  {
    rank: 1,
    name: "Google DeepMind",
    slug: "google-deepmind",
    summary: "Frontier AI research lab within Google scaling multimodal foundation models globally.",
    location: "London, UK",
    region: "eu",
    category: ["frontier", "bigtech"],
    models: ["Gemini Ultra", "Gemini Pro", "Gemini Nano", "Imagen", "Veo", "Nano Banana", "Lyria 3"],
    strategy: "Closed + selective open",
    valuation: "$300B+ (Alphabet revenue)",
    valuationNum: 300,
    leader: "Demis Hassabis",
    leaderX: "https://x.com/demishassabis",
    partnerships: "Google Search, Android, Workspace, Cloud",
    companyX: "https://x.com/GoogleDeepMind",
    domain: "deepmind.google",
    logoDomain: "google.com",
    color: "#4285F4",
    emoji: "🧪",
    latestNews: null
  },
  {
    rank: 2,
    name: "Meta",
    slug: "meta",
    summary: "Open-weight AI leader embedding large models across global consumer platforms.",
    location: "Menlo Park, USA",
    region: "us",
    category: ["frontier", "bigtech", "opensource"],
    models: ["Llama 4", "Llama 3", "Meta AI Assistant"],
    strategy: "Open-weight + proprietary",
    valuation: "$200B+ (revenue)",
    valuationNum: 200,
    leader: "Mark Zuckerberg",
    leaderX: "https://x.com/finkd",
    partnerships: "Facebook, Instagram, WhatsApp ecosystem",
    companyX: "https://x.com/Meta",
    domain: "meta.com",
    logoDomain: "meta.com",
    color: "#0668E1",
    emoji: "👁️",
    newsSearch: "Meta AI Llama",
    latestNews: null
  },
  {
    rank: 3,
    name: "ByteDance",
    slug: "bytedance",
    summary: "Chinese tech giant integrating foundation models across TikTok and enterprise tools.",
    location: "Beijing, China",
    region: "cn",
    category: ["bigtech"],
    models: ["Doubao LLM", "Seedance", "Seedream"],
    strategy: "Hybrid",
    valuation: "$400B+ (est.)",
    valuationNum: 400,
    leader: "Liang Rubo",
    leaderX: null,
    partnerships: "TikTok ecosystem, enterprise cloud services",
    companyX: "https://x.com/BytedanceTalk",
    domain: "bytedance.com",
    logoDomain: "tiktok.com",
    color: "#010101",
    emoji: "🎵",
    latestNews: null
  },
  {
    rank: 4,
    name: "OpenAI",
    slug: "openai",
    summary: "Consumer-first frontier AI lab commercializing GPT models at global scale.",
    location: "San Francisco, USA",
    region: "us",
    category: ["frontier"],
    models: ["GPT-4o", "o1", "o3", "ChatGPT", "DALL·E", "Sora"],
    strategy: "Closed API",
    valuation: "$157B+ (est.)",
    valuationNum: 157,
    leader: "Sam Altman",
    leaderX: "https://x.com/sama",
    partnerships: "Microsoft (Azure, Copilot), Apple (iOS integration)",
    companyX: "https://x.com/OpenAI",
    domain: "openai.com",
    logoDomain: "openai.com",
    color: "#10A37F",
    emoji: "🌀",
    latestNews: null
  },
  {
    rank: 5,
    name: "Anthropic",
    slug: "anthropic",
    summary: "AI safety-focused frontier lab building enterprise-aligned models.",
    location: "San Francisco, USA",
    region: "us",
    category: ["frontier"],
    models: ["Claude Opus", "Claude Sonnet", "Claude Haiku", "Claude Code"],
    strategy: "Closed API",
    valuation: "$60B+ (est.)",
    valuationNum: 60,
    leader: "Dario Amodei",
    leaderX: "https://x.com/darioamodei",
    partnerships: "Amazon (AWS Bedrock), Google Cloud",
    companyX: "https://x.com/AnthropicAI",
    domain: "anthropic.com",
    logoDomain: "anthropic.com",
    color: "#D4A574",
    emoji: "🛡️",
    latestNews: null
  },
  {
    rank: 6,
    name: "Alibaba",
    slug: "alibaba",
    summary: "Chinese cloud giant building sovereign AI stack for enterprise and government.",
    location: "Hangzhou, China",
    region: "cn",
    category: ["bigtech"],
    models: ["Qwen (Tongyi Qianwen)"],
    strategy: "Hybrid (open + proprietary)",
    valuation: "$130B+ (revenue)",
    valuationNum: 130,
    leader: "Eddie Wu",
    leaderX: null,
    partnerships: "Alibaba Cloud ecosystem",
    companyX: "https://x.com/AlibabaGroup",
    domain: "alibabagroup.com",
    logoDomain: "alibaba.com",
    color: "#FF6A00",
    emoji: "🏪",
    latestNews: null
  },
  {
    rank: 7,
    name: "Baidu",
    slug: "baidu",
    summary: "Chinese search leader integrating AI into national internet infrastructure.",
    location: "Beijing, China",
    region: "cn",
    category: ["bigtech"],
    models: ["ERNIE Bot"],
    strategy: "Closed + selective open",
    valuation: "$18B+ (revenue)",
    valuationNum: 18,
    leader: "Robin Li",
    leaderX: null,
    partnerships: "Baidu Search, Cloud",
    companyX: "https://x.com/Baidu_Inc",
    domain: "baidu.com",
    logoDomain: "baidu.com",
    color: "#2932E1",
    emoji: "🔍",
    latestNews: null
  },
  {
    rank: 8,
    name: "Tencent",
    slug: "tencent",
    summary: "Chinese platform conglomerate embedding AI into social and gaming ecosystems.",
    location: "Shenzhen, China",
    region: "cn",
    category: ["bigtech"],
    models: ["Hunyuan"],
    strategy: "Closed",
    valuation: "$85B+ (revenue)",
    valuationNum: 85,
    leader: "Pony Ma",
    leaderX: null,
    partnerships: "WeChat ecosystem",
    companyX: "https://x.com/TencentGlobal",
    domain: "tencent.com",
    logoDomain: "tencent.com",
    color: "#12B7F5",
    emoji: "💬",
    latestNews: null
  },
  {
    rank: 9,
    name: "Huawei",
    slug: "huawei",
    summary: "Infrastructure heavyweight focused on sovereign AI compute and models.",
    location: "Shenzhen, China",
    region: "cn",
    category: ["bigtech", "infra"],
    models: ["Pangu 5.5", "openPangu"],
    strategy: "Hybrid (open + enterprise)",
    valuation: "$118B+ (revenue)",
    valuationNum: 118,
    leader: "Ren Zhengfei",
    leaderX: null,
    partnerships: "Huawei Cloud, state-linked deployments",
    companyX: "https://x.com/Huawei",
    domain: "huawei.com",
    logoDomain: "huawei.com",
    color: "#CF0A2C",
    emoji: "📡",
    latestNews: null
  },
  {
    rank: 10,
    name: "xAI",
    slug: "xai",
    summary: "Elon Musk's AI venture integrating real-time models with social and aerospace platforms.",
    location: "Austin, USA",
    region: "us",
    category: ["frontier"],
    models: ["Grok 4", "Grok-3"],
    strategy: "Closed consumer + API",
    valuation: "$250B (SpaceX merger)",
    valuationNum: 250,
    leader: "Elon Musk",
    leaderX: "https://x.com/elonmusk",
    partnerships: "X platform, SpaceX (merged Feb 2026)",
    companyX: "https://x.com/xai",
    domain: "x.ai",
    logoDomain: "x.com",
    color: "#1DA1F2",
    emoji: "🚀",
    newsSearch: "xAI Grok",
    latestNews: null
  },
  {
    rank: 11,
    name: "Mistral AI",
    slug: "mistral",
    summary: "European challenger known for efficient open-weight frontier models.",
    location: "Paris, France",
    region: "eu",
    category: ["frontier", "opensource"],
    models: ["Mistral Large", "Mixtral", "Le Chat"],
    strategy: "Open-weight + API",
    valuation: "$14B+ (est.)",
    valuationNum: 14,
    leader: "Arthur Mensch",
    leaderX: "https://x.com/arthurmensch",
    partnerships: "Microsoft Azure distribution",
    companyX: "https://x.com/MistralAI",
    domain: "mistral.ai",
    logoDomain: "mistral.ai",
    color: "#FF7000",
    emoji: "🌬️",
    latestNews: null
  },
  {
    rank: 12,
    name: "Cohere",
    slug: "cohere",
    summary: "Enterprise-focused LLM provider optimized for retrieval and business use.",
    location: "Toronto, Canada",
    region: "other",
    category: ["frontier"],
    models: ["Command R family", "Command A", "Aya Vision"],
    strategy: "Closed enterprise API",
    valuation: "$7B+ (est.)",
    valuationNum: 7,
    leader: "Aidan Gomez",
    leaderX: "https://x.com/aidangomez",
    partnerships: "Oracle, AWS Bedrock",
    companyX: "https://x.com/Cohere",
    domain: "cohere.com",
    logoDomain: "cohere.com",
    color: "#39594D",
    emoji: "🔗",
    latestNews: null
  },
  {
    rank: 13,
    name: "AI21 Labs",
    slug: "ai21",
    summary: "Israeli AI lab focused on modular and hybrid language model architectures.",
    location: "Tel Aviv, Israel",
    region: "other",
    category: ["frontier"],
    models: ["Jamba 1.7", "Jamba 1.5"],
    strategy: "Hybrid",
    valuation: "$1.4B+ (est.)",
    valuationNum: 1.4,
    leader: "Ori Goshen",
    leaderX: null,
    partnerships: "Enterprise integrations, AWS",
    companyX: "https://x.com/AI21Labs",
    domain: "ai21.com",
    logoDomain: "ai21.com",
    color: "#6C3AFF",
    emoji: "🦕",
    latestNews: null
  },
  {
    rank: 14,
    name: "Stability AI",
    slug: "stability",
    summary: "Open generative AI company best known for image diffusion models.",
    location: "London, UK",
    region: "eu",
    category: ["opensource"],
    models: ["Stable Diffusion"],
    strategy: "Open-weight",
    valuation: "$1B+ (fluctuating)",
    valuationNum: 1,
    leader: "Prem Akkaraju",
    leaderX: null,
    partnerships: "Creative platforms ecosystem",
    companyX: "https://x.com/StabilityAI",
    domain: "stability.ai",
    logoDomain: "stability.ai",
    color: "#A855F7",
    emoji: "🎨",
    latestNews: null
  },
  {
    rank: 15,
    name: "Moonshot AI",
    slug: "moonshot",
    summary: "Chinese startup known for long-context language models (Kimi).",
    location: "Beijing, China",
    region: "cn",
    category: ["frontier"],
    models: ["Kimi K2.5", "Kimi"],
    strategy: "Closed consumer",
    valuation: "$4.3B+ (est.)",
    valuationNum: 4.3,
    leader: "Yang Zhilin",
    leaderX: null,
    partnerships: "Chinese consumer ecosystem",
    companyX: null,
    domain: "moonshot.cn",
    logoDomain: "moonshot.cn",
    color: "#FFD700",
    emoji: "🌙",
    latestNews: null
  },
  {
    rank: 16,
    name: "01.AI",
    slug: "01ai",
    summary: "Venture-backed Chinese foundation model startup founded by Kai-Fu Lee.",
    location: "Beijing, China",
    region: "cn",
    category: ["frontier", "opensource"],
    models: ["Yi models"],
    strategy: "Open-weight + API",
    valuation: "<$2B (est.)",
    valuationNum: 1.5,
    leader: "Kai-Fu Lee",
    leaderX: "https://x.com/kflee",
    partnerships: "Chinese enterprise ecosystem",
    companyX: null,
    domain: "01.ai",
    logoDomain: "01.ai",
    color: "#00D4AA",
    emoji: "🎯",
    latestNews: null
  },
  {
    rank: 17,
    name: "DeepSeek",
    slug: "deepseek",
    summary: "Chinese AI research lab producing highly efficient open-weight reasoning models that shook global markets.",
    location: "Hangzhou, China",
    region: "cn",
    category: ["frontier", "opensource"],
    models: ["DeepSeek-V3", "DeepSeek-R1", "DeepSeek Coder"],
    strategy: "Open-weight",
    valuation: "Private (est. ~$2B+)",
    valuationNum: 2,
    leader: "Liang Wenfeng",
    leaderX: null,
    partnerships: "Open-source community, Chinese enterprise",
    companyX: "https://x.com/deepseek_ai",
    domain: "deepseek.com",
    logoDomain: "deepseek.com",
    color: "#4F46E5",
    emoji: "🐋",
    latestNews: null
  },
  {
    rank: 18,
    name: "Samsung",
    slug: "samsung",
    summary: "Korean electronics giant integrating on-device AI across consumer hardware.",
    location: "Seoul, South Korea",
    region: "other",
    category: ["bigtech", "infra"],
    models: ["Samsung Gauss 2", "Samsung Gauss"],
    strategy: "Closed + on-device",
    valuation: "$210B+ (revenue)",
    valuationNum: 210,
    leader: "Jong-Hee Han",
    leaderX: null,
    partnerships: "Galaxy ecosystem, Google partnership",
    companyX: "https://x.com/Samsung",
    domain: "samsung.com",
    logoDomain: "samsung.com",
    color: "#1428A0",
    emoji: "📱",
    newsSearch: "Samsung Gauss AI",
    latestNews: null
  },
  {
    rank: 19,
    name: "NVIDIA",
    slug: "nvidia",
    summary: "Dominant AI compute infrastructure provider powering the entire foundation model ecosystem.",
    location: "Santa Clara, USA",
    region: "us",
    category: ["infra"],
    models: ["NeMo", "NVIDIA AI Foundations"],
    strategy: "Platform + open tools",
    valuation: "$3T+ (market cap)",
    valuationNum: 3000,
    leader: "Jensen Huang",
    leaderX: "https://x.com/JensenHuang",
    partnerships: "Every major AI lab, cloud providers, sovereign AI programs",
    companyX: "https://x.com/nvidia",
    domain: "nvidia.com",
    logoDomain: "nvidia.com",
    color: "#76B900",
    emoji: "🔥",
    newsSearch: "NVIDIA AI GPU",
    latestNews: null
  },
  {
    rank: 20,
    name: "Amazon (AWS)",
    slug: "amazon-aws",
    summary: "Cloud infrastructure giant hosting and distributing frontier models via Bedrock marketplace.",
    location: "Seattle, USA",
    region: "us",
    category: ["bigtech", "infra"],
    models: ["Amazon Nova", "Amazon Titan", "AWS Bedrock"],
    strategy: "Platform + marketplace",
    valuation: "$717B+ (revenue)",
    valuationNum: 717,
    leader: "Andy Jassy",
    leaderX: "https://x.com/ajassy",
    partnerships: "Anthropic, Cohere, Meta, Stability AI",
    companyX: "https://x.com/awscloud",
    domain: "aws.amazon.com",
    logoDomain: "amazon.com",
    color: "#FF9900",
    emoji: "☁️",
    newsSearch: "Amazon AWS Bedrock AI",
    latestNews: null
  },
  {
    rank: 21,
    name: "Microsoft",
    slug: "microsoft",
    summary: "Global tech giant deeply integrated with OpenAI, embedding AI across its entire product stack.",
    location: "Redmond, USA",
    region: "us",
    category: ["bigtech", "infra"],
    models: ["Copilot", "Phi family", "Azure AI"],
    strategy: "Platform + partnership",
    valuation: "$3T+ (market cap)",
    valuationNum: 3000,
    leader: "Satya Nadella",
    leaderX: "https://x.com/satyanadella",
    partnerships: "OpenAI, Mistral AI, GitHub, LinkedIn",
    companyX: "https://x.com/Microsoft",
    domain: "microsoft.com",
    logoDomain: "microsoft.com",
    color: "#00A4EF",
    emoji: "🪟",
    newsSearch: "Microsoft Copilot AI",
    latestNews: null
  },
  {
    rank: 22,
    name: "Apple",
    slug: "apple",
    summary: "Consumer tech leader integrating on-device AI intelligence across its ecosystem.",
    location: "Cupertino, USA",
    region: "us",
    category: ["bigtech"],
    models: ["Apple Intelligence", "Ajax/MM1"],
    strategy: "Closed on-device + cloud",
    valuation: "$3.5T+ (market cap)",
    valuationNum: 3500,
    leader: "Tim Cook",
    leaderX: "https://x.com/tim_cook",
    partnerships: "OpenAI (ChatGPT integration), on-device ecosystem",
    companyX: "https://x.com/Apple",
    domain: "apple.com",
    logoDomain: "apple.com",
    color: "#555555",
    emoji: "🍎",
    newsSearch: "Apple Intelligence AI",
    latestNews: null
  }
];

// RSS feeds for AI news
const NEWS_FEEDS = [
  {
    name: "TechCrunch AI",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    icon: "📰"
  },
  {
    name: "The Verge AI",
    url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    icon: "⚡"
  },
  {
    name: "MIT Tech Review",
    url: "https://www.technologyreview.com/feed/",
    icon: "🎓"
  },
  {
    name: "Ars Technica AI",
    url: "https://feeds.arstechnica.com/arstechnica/technology-lab",
    icon: "🔬"
  },
  {
    name: "VentureBeat AI",
    url: "https://venturebeat.com/category/ai/feed/",
    icon: "📊"
  }
];

// Signal type classification keywords
const SIGNAL_KEYWORDS = {
  launch: ["launch", "release", "announce", "unveil", "introduce", "debut", "ship", "model", "upgrade", "version", "update", "rollout", "preview"],
  funding: ["funding", "invest", "valuation", "raise", "round", "billion", "million", "capital", "ipo", "revenue", "profit"],
  regulation: ["regulation", "regulate", "ban", "law", "policy", "government", "congress", "eu act", "safety", "compliance", "executive order", "legislation"],
  partnership: ["partner", "deal", "acquisition", "merge", "collaborate", "alliance", "agreement", "integration", "joint venture"],
  infra: ["chip", "gpu", "data center", "compute", "infrastructure", "hardware", "semiconductor", "training", "cluster"]
};
